require("./tests/test-sequence.js")
require("./tests/test-sequence-operator.js")
require("./tests/test-evaluator.js")
require("./tests/test-sequence-player.js")
require("./tests/test-operator.js")
require("./tests/test-run-cases.js")
