#pragma once

#include "RenderNode.hpp"
#include "CycleRenderNode.hpp"
#include "NormalizeCycleRenderNode.hpp"
#include "SliceRenderNode.hpp"
#include "WeightedPatternRenderNode.hpp"
#include "StretchRenderNode.hpp"
#include "ShiftRenderNode.hpp"
#include "StructRenderNode.hpp"
#include "AddRenderNode.hpp"
#include "ScaleRenderNode.hpp"
#include "TruncRenderNode.hpp"
#include "TimelineRenderNode.hpp"
#include "StackRenderNode.hpp"
